/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 LEGION.glb -T 
Files: LEGION.glb [977.37KB] > D:\Programming\LEGIONPRO-PROJECT\LENOVO-LEGION-3D-WEBSITE\lenovo-3d-website\public\Models\LEGION-transformed.glb [260.32KB] (73%)
*/

import React from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

export function Legion(props) {
  const { nodes, materials } = useGLTF('/Models/LEGION-transformed.glb');

  const texture = useTexture('/Header/images/Legion-3.webp')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Geom3D.geometry} material={materials['11_Legion_7_Hero_Top_View']} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_1.geometry} material={materials.PaletteMaterial001} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_2.geometry} material={materials.PaletteMaterial002} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_3.geometry} material={materials.PaletteMaterial003} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_4.geometry} material={materials.PaletteMaterial004} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_5.geometry} material={materials.PaletteMaterial005} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_6.geometry} material={materials.PaletteMaterial006} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_7.geometry} material={materials.PaletteMaterial007} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_8.geometry} material={materials.PaletteMaterial008} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_9.geometry} material={materials['lenovo-logo']} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_10.geometry} material={materials['3c3486456c6394']} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_11.geometry} material={materials['_Color M09_']} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_Lenovo_Legion_7.geometry} material={nodes.Geom3D_Lenovo_Legion_7.material} position={[0.15, -0.01, -0.151]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes['Geom3D_GEFORCE#1'].geometry} material={materials.PaletteMaterial009} position={[0.197, 0.015, -0.182]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0} />
      
      <mesh geometry={nodes.Geom3D_13.geometry} material={materials.PaletteMaterial011} position={[0.162, 0.003, -0.163]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_14.geometry} material={materials.PaletteMaterial012} position={[0.16, 0.253, -0.384]} rotation={[3.135, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_15.geometry} material={materials.PaletteMaterial013} position={[0.16, 0.253, -0.384]} rotation={[3.135, 0, 0]} scale={0.025} />
      <mesh geometry={nodes.Geom3D_16.geometry} material={materials.PaletteMaterial014} position={[0.487, 0.2149, -0.386]} rotation={[3.135, 0, 0]} scale={0.025} />
    </group>
  )
}

useGLTF.preload('/Models/LEGION-transformed.glb')




// <mesh geometry={nodes.Geom3D_12.geometry} material={materials.PaletteMaterial010} position={[0.351, 0.031, -0.383]} rotation={[0, 0, Math.PI / 2]} scale={[0.009, 0.009, 0.005]} >
//         <meshBasicMaterial map={texture}/>
//       </mesh>
