/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Lenovo.glb -T 
Files: Lenovo.glb [462.63KB] > D:\Programming\LEGIONPRO-PROJECT\LENOVO-LEGION-3D-WEBSITE\lenovo-3d-website\public\Models\Lenovo-transformed.glb [28.73KB] (94%)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Lenovo(props) {
  const { nodes, materials } = useGLTF('/Models/Lenovo-transformed.glb')
  return (
    <group {...props} dispose={null}>
      
      <mesh geometry={nodes.Lenovo7pro.geometry} material={nodes.Lenovo7pro.material} />
    </group>
  )
}

useGLTF.preload('/Models/Lenovo-transformed.glb')
